name: Linux Smoke Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    name: Test on Ubuntu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # Install bats
        sudo apt-get update
        sudo apt-get install -y bats
        
        # Install ripgrep for search tools
        sudo apt-get install -y ripgrep
        
        # Install other optional dependencies
        sudo apt-get install -y jq fzf bat
    
    - name: Run setup script
      run: ./setup.sh
    
    - name: Run all tests
      run: make test
    
    - name: Check test coverage
      run: make coverage || true